LKLK/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from projectapp.views import ProjectListView

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('joins/', include('joinapp.urls')),
    path('feeds/', include('feedapp.urls')),
    path('teams/', include('teamapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

feedapp/urls.py
from django.urls import path

from feedapp.views import FeedCreateView, FeedUpdateView, FeedDetailView, FeedListView, FeedDeleteView

app_name = "feedapp"

urlpatterns = [
    path('create/', FeedCreateView.as_view(), name='create'),
    path('update/<int:pk>', FeedUpdateView.as_view(), name='update'),
    path('detail/<int:pk>', FeedDetailView.as_view(), name='detail'),
    path('list/', FeedListView.as_view(), name='list'),
    path('delete/<int:pk>', FeedDeleteView.as_view(), name='delete'),
]

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from feedapp.models import Feed
from projectapp.models import Project


class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='comment')
    feed = models.ForeignKey(Feed, on_delete=models.SET_NULL, null=True, related_name='comment')


    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)

    def approve(self):
        self.save()

    def __str__(self):
        return self.content

feedapp/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Feed(models.Model):
    writer = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='feed', null=True)

    title = models.CharField(max_length=200, null=True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='feed', null=True)
    #image = models.ImageField(upload_to='feed/', null=True)
    content = RichTextField(null=True)

    created_at = models.DateField(auto_now_add=True, null=True)

teamapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from projectapp.models import Project


class Team(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team')
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='team')

    # member를 다룰 수 있는 자료형으로 반복문 돌릴 수 있도록
    member1 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_1', null=True)
    member2 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_2', null=True)
    member3 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_3', null=True)
    member4 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_4', null=True)
    member5 = models.ForeignKey(User, on_delete=models.CASCADE, related_name='team_5', null=True)

    #count = models.IntegerField(default=1, null=True)
    # 하나의 user가 프로젝트를 한번만 team할 수 있도록
    class Meta:
        unique_together = ('user', 'project')

feedapp/forms.py
from django.forms import ModelForm

from feedapp.models import Feed


class FeedCreationForm(ModelForm):
    class Meta:
        model = Feed
        fields = ['title',  'content']

feedapp/views.py
from django.contrib.auth.decorators import login_required

# Create your views here.
from django.contrib.auth.models import User
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView
from django.views.generic.edit import FormMixin

from commentapp.forms import CommentCreationForm
from commentapp.models import Comment
from feedapp.decorators import feed_ownership_required
from feedapp.forms import FeedCreationForm
from feedapp.models import Feed
from joinapp.models import Join
from projectapp.models import Project
from teamapp.models import Team


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class FeedCreateView(CreateView):
    model = Feed
    form_class = FeedCreationForm
    template_name = 'feedapp/create.html'

    def form_valid(self, form):
        temp_post = form.save(commit=False)
        temp_post.writer = self.request.user
        temp_post.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('feedapp:detail', kwargs={'pk': self.object.pk})

class FeedDetailView(DetailView):
    model = Feed
    context_object_name = 'target_post'
    template_name = 'feedapp/detail.html'

    def get_context_data(self, **kwargs):
        project = get_object_or_404(Project, pk=self.request.GET.get('project_pk'))
        team = Team.objects.filter(user=project.writer, project=project)
        return super(FeedDetailView, self).get_context_data(team=team, **kwargs)

@method_decorator(feed_ownership_required, 'get')
@method_decorator(feed_ownership_required, 'post')
class FeedUpdateView(UpdateView):
    model = Feed
    context_object_name = 'target_post'
    form_class = FeedCreationForm
    template_name = 'feedapp/update.html'

    def get_success_url(self):
        return reverse('feedapp:detail', kwargs={'pk': self.object.pk})

@method_decorator(feed_ownership_required, 'get')
@method_decorator(feed_ownership_required, 'post')
class FeedDeleteView(DeleteView):
    model = Feed
    context_object_name = 'target_post'
    success_url = reverse_lazy('feedapp:list')
    template_name = 'feedapp/delete.html'

class FeedListView(ListView, FormMixin):
    model = Feed
    form_class = CommentCreationForm
    context_object_name = 'post_list'
    template_name = 'feedapp/list.html'
    paginate_by = 25
    # def get(self, request):
    #     from django.shortcuts import render
    #
    #     if request.method == 'GET':
    #         project_name = request.GET.get('project_name')
    #         data = {'project_name':project_name,}
    #         return render(request, "feedapp/list.html",data)
    #     else:
    #         return render(request, "feedapp/list.html",{})

    #def get(self, request):
    #    from django.shortcuts import render
    #    team_list = Team.objects.all()
    #    if request.method == 'GET':
    #        project_name = request.GET.get('project_name')
    #        data = {'project_name':project_name,'join_list':join_list}
    #    else:
    #        data = {'join_list':join_list}
    #    return render(request, "feedapp/list.html", data)

    def get_context_data(self, **kwargs):
        project = get_object_or_404(Project, pk=self.request.GET.get('project_pk'))
        #if project pk가 없다면 - 전체 출력
        team_list = Team.objects.filter(user=project.writer, project=project)
        feed_list = Feed.objects.filter(project=project)
        comment_list = Comment.objects.filter(project=project).order_by("-created_at")
        # if not(team.exists()):
        #     team = None

        return super(FeedListView, self).get_context_data(team_list=team_list, comment_list=comment_list, feed_list=feed_list, **kwargs)


    # def get_context_data(self, **kwargs):
    #     join_list = Join.objects.all()
    #     return super(FeedListView, self).get_context_data(join_list=join_list, **kwargs)

feedapp/templates/feedapp/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Feed Create</h4>
    </div>
    <form action="{% url 'feedapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

feedapp/templates/feedapp/delete.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Delete Feed : {{ target_post.title }}</h4>
    </div>
    <form action="{% url 'feedapp:delete' pk=target_post.pk %}" method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}

feedapp/templates/feedapp/detail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div>
    <div style="text-align:center; max-width:500px; margin: 4rem auto">
       <h1>
           글 제목 : {{target_post.title}}
       </h1>
        <h4>
            글쓴이 : {{target_post.writer}}
        </h4>
        <h4>
            글 종류 : {{target_post.type}}
        </h4>
        <p>
            본문 : {{target_post.content | safe}}
        </p>
        gdgd{{team}}
        {% if target_post.image %}
            <img src="{{target_post.image.url}}" alt="">
        {% endif %}



        {% if target_post.writer == user %}
            <a href="{% url 'feedapp:update' pk=target_post.pk %}">
                <p>Update Post</p>
            </a>
            <a href="{% url 'feedapp:delete' pk=target_post.pk %}">
                <p>Delete Post</p>
            </a>
        {% endif %}

        <a href="{% url 'feedapp:list' %}">
            <p>list</p>
        </a>

    </div>
</div>
{% endblock %}

feedapp/templates/feedapp/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container"  >
    <a href="{% url 'feedapp:create' %}">post</a>
<!--    {% for post in post_list %}-->
<!--        <div  class="detail_page detail_component">-->
<!--          <a href="{% url 'feedapp:detail' pk=post.pk%}" class="size4-link">{{post.title}}</a>-->
<!--          <div class="date_detail">-->
<!--            <div class="text-label big">게시일 :</div>-->
<!--            <div class="text-label date">{{post.created_at}}</div>-->
<!--            <div class="nav-kit-divider"></div>-->
<!--            <div class="text-label big">글쓴이 :</div>-->
<!--            <div class="text-label date">{{post.writer}}</div>-->
<!--          </div>-->
<!--          <div class="paragraph-70">{{post.content | safe}}</div>-->
<!--        </div>-->
<!--    {% endfor %}-->

    <h1> 프로젝트 정보 </h1>
<!--    list는 이미 필터링 되어 있어서 한번만 돈다.-->
<!--    프로젝트 정보 -->
    {% for team in team_list %}
        leader : {{team.project.writer}}<br>
        team : {{team.member1}}<br>
        team : {{team.member2}}<br>
        team : {{team.member3}}<br>
        team : {{team.member4}}<br>
        team : {{team.member5}}<br>
        <hr>
        title : {{team.project.title}}<br>
        created_at : {{team.project.created_at}}<br>
        content : {{team.project.content}}<br>
        <img src="{{team.project.image.url}}"><br>
        <img src="{{team.project.image2.url}}"><br>
        <img src="{{team.project.image3.url}}"><br>
        <br><hr>

        {% for comment in comment_list %}
            {% if comment.feed is None %}
                {% include 'commentapp/detail.html' with comment=comment %}
            {% endif %}
        {% endfor%}


        <br><br>
        <h3>프로젝트의 각 피드들</h3>
        <!--    각 피드들-->
        {% for feed in feed_list %}
            제목 : {{feed.title}}  글쓴이 : {{feed.writer}}<hr>
            {{feed.content | safe}}<hr>
            {% include 'commentapp/create.html' with project=team.project feed=feed %}

            <!--    각 피드의 댓글들     -->
            {% for comment in comment_list %}
                {% if comment.feed == feed %}
                    {% include 'commentapp/detail.html' with comment=comment %}
                {% endif %}
            {% endfor%}
        {% endfor %}
        <hr>

    {% endfor %}

</div>

{% endblock %}

feedapp/templates/feedapp/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>Feed Update</h4>
    </div>
    <form action="{% url 'feedapp:update' pk=target_post.pk %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.media }}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
    </form>
</div>
{% endblock %}