LKLK/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from projectapp.views import ProjectListView

urlpatterns = [
    path('', ProjectListView.as_view(), name='home'),

    path('admin/', admin.site.urls),
    path('accounts/', include('accountapp.urls')),
    path('profiles/', include('profileapp.urls')),
    path('projects/', include('projectapp.urls')),
    path('joins/', include('joinapp.urls')),
    path('feeds/', include('feedapp.urls')),
    path('teams/', include('teamapp.urls')),
    path('comments/', include('commentapp.urls')),

    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commentapp/urls.py
from django.urls import path

from commentapp.views import CommentCreateView, CommentDeleteView

app_name = "commentapp"

urlpatterns = [
    path('create/', CommentCreateView.as_view(), name='create'),
    path('delete/<int:pk>', CommentDeleteView.as_view(), name='delete'),

]

commentapp/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from feedapp.models import Feed
from projectapp.models import Project


class Comment(models.Model):
    project = models.ForeignKey(Project, on_delete=models.SET_NULL, null=True, related_name='comment')
    feed = models.ForeignKey(Feed, on_delete=models.SET_NULL, null=True, related_name='comment')


    writer = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='comment')

    content = models.TextField(null=False)

    created_at = models.DateTimeField(auto_now=True)

    def approve(self):
        self.save()

    def __str__(self):
        return self.content

commentapp/forms.py
from django.forms import ModelForm

from commentapp.models import Comment


class CommentCreationForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

commentapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

# Create your views here.
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, DeleteView, ListView, DetailView, UpdateView

from commentapp.decorators import comment_ownership_required
from commentapp.forms import CommentCreationForm
from commentapp.models import Comment
from feedapp.models import Feed
from projectapp.models import Project
from teamapp.models import Team


@method_decorator(login_required, 'get')
@method_decorator(login_required, 'post')
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentCreationForm
    template_name = 'commentapp/create.html'
    context_object_name = 'target_comment'

    def form_valid(self, form):
        temp_comment = form.save(commit=False)
        temp_comment.project = Project.objects.get(pk=self.request.POST['project_pk'])
        temp_comment.feed = Feed.objects.get(pk=self.request.POST['feed_pk'])
        temp_comment.writer = self.request.user
        temp_comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('projectapp:detail', kwargs={'pk': self.request.POST['project_pk']})


# class CommentDetailView(DetailView):
#     model = Comment
#     template_name = 'commentapp/detail.html'
#     context_object_name = 'comment'
#     def get_context_data(self, **kwargs):
#         project = get_object_or_404(Project, pk=self.request.GET.get('project_pk'))
#         comment = Comment.object.filter(project=project)
#         team = Team.objects.all()
#         return super(CommentDetailView, self).get_context_data(comment=comment, team=team, project=project, **kwargs)

class CommentDeleteView(DeleteView):
    model = Comment
    context_object_name = 'target_comment'
    #success_url = reverse_lazy('commentapp:list')
    template_name = 'commentapp/delete.html'

    def get_success_url(self):
        return reverse('home')
# class CommentListView(ListView):
#     model = Comment
#     context_object_name = 'comment_list'
#     template_name = 'commentapp/list.html'
#     paginate_by = 25
#

commentapp/templates/commentapp/create.html
{% load bootstrap4 %}
{% block content %}

<div style="text-align:center; max-width:500px; margin: 4rem auto">
    <div class="mb-4">
        <h4>피드의 댓글쓰기</h4>
    </div>
    <form action="{% url 'commentapp:create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-dark rounded-pill col-6 mt-3">
        <input type="hidden" name="project_pk" value="{{project.pk}}">
        <input type="hidden" name="feed_pk" value="{{feed.pk}}">
    </form>
</div>
{% endblock %}

commentapp/templates/commentapp/delete.html
{% extends 'base.html' %}

{% block content %}

    <div style="text-align: center; max-width: 500px; margin: 4rem auto">
        <div class="mb-4">
            <h4>Delete Comment : {{ target_comment.content }}</h4>
        </div>
        <form action="{% url 'commentapp:delete' pk=target_comment.pk %}" method="post">
            {% csrf_token %}
            <input type="submit" class="btn btn-danger rounded-pill col-6 mt-3">
        </form>
    </div>

{% endblock %}

commentapp/templates/commentapp/detail.html
<div style="border: 1px solid; text-align: left; padding: 4%; margin: 1rem 0; border-radius: 1rem;
            border-color: #bbb;">
     <div>
         <strong>
             {{ comment.writer }}
         </strong>
         &nbsp&nbsp&nbsp
         {{ comment.created_at }}
     </div>
     <div style="margin: 1rem 0;">
         {{ comment.content }}
     </div>

    {% if comment.writer == user %}
    <div style="text-align: right">
        <a href="{% url 'commentapp:delete' pk=comment.pk %}"
            class="btn btn-danger rounded-pill">
            Delete
        </a>
    </div>
    {% endif %}
 </div>